In [1]:
import numpy as np
import pandas as pd

In [36]:
df = pd.read_csv("Text_Preprocessing.csv")

df.head()

Unnamed: 0  no                                              judul  \
0           0   3  usaha kerajinan gerabah untuk meningkatakan pe...   
1           1   3  peranan industri gerabah keramik sebagai suatu...   
2           2   3  industri kerajinan gerabah dan peranannya seba...   
3           3   3  peranan industri kecil warangka keris dalam me...   
4           4   3  bimbingan agama islam terhadap remaja dalam ke...   

                                        judul_tokens  \
0  ['usaha', 'kerajinan', 'gerabah', 'untuk', 'me...   
1  ['peranan', 'industri', 'gerabah', 'keramik', ...   
2  ['industri', 'kerajinan', 'gerabah', 'dan', 'p...   
3  ['peranan', 'industri', 'kecil', 'warangka', '...   
4  ['bimbingan', 'agama', 'islam', 'terhadap', 'r...   

                           judul_tokens_fdist  \
0  <FreqDist with 19 samples and 19 outcomes>   
1  <FreqDist with 18 samples and 18 outcomes>   
2  <FreqDist with 17 samples and 17 outcomes>   
3    <FreqDist with 9 samples and 9 outcomes>   
4  <FreqDist with 14 samples and 14 outcomes>   

                                    judul_tokens_WSW  \
0  ['usaha', 'kerajinan', 'gerabah', 'meningkatak...   
1  ['peranan', 'industri', 'gerabah', 'keramik', ...   
2  ['industri', 'kerajinan', 'gerabah', 'peranann...   
3  ['peranan', 'industri', 'warangka', 'keris', '...   
4  ['bimbingan', 'agama', 'islam', 'remaja', 'kel...   

                                judul_tokens_stemmed  
0  ['usaha', 'rajin', 'gerabah', 'meningkatakan',...  
1  ['peran', 'industri', 'gerabah', 'keramik', 's...  
2  ['industri', 'rajin', 'gerabah', 'peran', 'sum...  
3  ['peran', 'industri', 'warangka', 'keris', 'ti...  
4  ['bimbing', 'agama', 'islam', 'remaja', 'kelua...

In [142]:
df.shape
df['no'].value_counts()
# df['judul'][0]

6    8735
3    8578
8    7402
2    4950
7    2623
1    2266
5    1640
0    1449
9    1448
4    1045
Name: no, dtype: int64

In [139]:
df.shape

(40136, 7)

In [ ]:
from sklearn.model_selection import train_test_split

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
data_1 = [df['judul'][9]]

# create the transform
vectorizer = CountVectorizer()

vectorizer.fit(data_1)


print(vectorizer.vocabulary_) 

{'studi': 17, 'komparatif': 12, 'tentang': 18, 'pelaksanaan': 14, 'pendidikan': 15, 'agama': 0, 'islam': 9, 'bagi': 2, 'anak': 1, 'dalam': 5, 'lingkungan': 13, 'keluarga': 11, 'guru': 8, 'sd': 16, 'dan': 6, 'umum': 19, 'di': 7, 'kecamatan': 10, 'bambanglipuro': 3, 'bantul': 4}


In [50]:
"""encode document"""
vector = vectorizer.transform(data_1)
print(vector)

  (0, 0)	2
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (0, 7)	1
  (0, 8)	2
  (0, 9)	2
  (0, 10)	1
  (0, 11)	2
  (0, 12)	1
  (0, 13)	2
  (0, 14)	1
  (0, 15)	1
  (0, 16)	2
  (0, 17)	1
  (0, 18)	1
  (0, 19)	1


In [79]:
import string
from nltk.corpus import stopwords
def text_cleaning(a):
 remove_punctuation = [char for char in str(a) if char not in string.punctuation]
 #print(remove_punctuation)
 remove_punctuation=''.join(remove_punctuation)
 #print(remove_punctuation)   
 return [word for word in remove_punctuation.split() if word.lower() not in stopwords.words('indonesian')]

In [80]:
print(df.iloc[:,2].apply(text_cleaning))

0        [usaha, kerajinan, gerabah, meningkatakan, pen...
1        [peranan, industri, gerabah, keramik, sisi, da...
2        [industri, kerajinan, gerabah, peranannya, sum...
3        [peranan, industri, warangka, keris, meningkat...
4        [bimbingan, agama, islam, remaja, keluarga, mu...
                               ...                        
40131                               [angel, in, the, rain]
40132                                 [the, hunger, games]
40133                              [marrying, mr, perfect]
40134                        [bad, boy, for, little, girl]
40135    [tinjauan, yuridis, pelaksanaan, program, jami...
Name: judul, Length: 40136, dtype: object


In [92]:
from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer=text_cleaning).fit(df['judul_tokens_stemmed'].values.astype('U')) 
  
#print(len(bow_transformer.vocabulary_))   
bow_transformer.vocabulary_

{'usaha': 20576,
 'rajin': 15886,
 'gerabah': 6211,
 'meningkatakan': 11848,
 'masyarakat': 11532,
 'desa': 4198,
 'kasongan': 8924,
 'kalurahan': 8694,
 'bangunjiwo': 1739,
 'camat': 3035,
 'kasihan': 8919,
 'kabupaten': 8568,
 'bantul': 1775,
 'daerah': 3862,
 'istimewa': 8022,
 'yogyakarta': 21317,
 'peran': 14436,
 'industri': 7633,
 'keramik': 9317,
 'sisi': 17917,
 'daya': 4008,
 'tarik': 19171,
 'kembang': 9208,
 'pariwisata': 13926,
 'diy': 4512,
 'sumber': 18669,
 'rumah': 16660,
 'tangga': 19108,
 'warangka': 20901,
 'keris': 9348,
 'tingkat': 19751,
 'bimbing': 2367,
 'agama': 248,
 'islam': 7984,
 'remaja': 16206,
 'keluarga': 9190,
 'muslim': 12635,
 'panajang': 13755,
 'rejo': 16148,
 'pundong': 15615,
 'hubung': 7224,
 'lokasi': 10848,
 'gembala': 6134,
 'infeksi': 7642,
 'cacing': 2990,
 'sapi': 16979,
 'siti': 17947,
 'mulyo': 12554,
 'piyungan': 14832,
 'laksana': 10341,
 'ibadah': 7316,
 'buruh': 2938,
 'bangun': 1733,
 'sumberagung': 18670,
 'jetis': 8339,
 'lembaga

In [93]:
title_bow = bow_transformer.transform(df['judul_tokens_stemmed'].values.astype('U'))

print(title_bow)

  (0, 1739)	1
  (0, 1775)	1
  (0, 3035)	1
  (0, 3862)	1
  (0, 4198)	1
  (0, 6211)	1
  (0, 8022)	1
  (0, 8568)	1
  (0, 8694)	1
  (0, 8919)	1
  (0, 8924)	1
  (0, 11532)	1
  (0, 11848)	1
  (0, 15886)	1
  (0, 20576)	1
  (0, 21317)	1
  (1, 1775)	1
  (1, 3035)	1
  (1, 4008)	1
  (1, 4198)	1
  (1, 4512)	1
  (1, 6211)	1
  (1, 7633)	1
  (1, 8919)	1
  (1, 8924)	1
  :	:
  (40131, 15868)	1
  (40131, 19614)	1
  (40132, 5997)	1
  (40132, 7267)	1
  (40132, 19614)	1
  (40133, 11455)	1
  (40133, 12420)	1
  (40133, 14480)	1
  (40134, 1570)	1
  (40134, 2679)	1
  (40134, 5786)	1
  (40134, 6304)	1
  (40134, 10800)	1
  (40135, 1775)	1
  (40135, 3862)	1
  (40135, 8154)	1
  (40135, 8568)	1
  (40135, 9319)	1
  (40135, 10341)	1
  (40135, 12806)	1
  (40135, 13588)	1
  (40135, 15416)	1
  (40135, 17224)	1
  (40135, 19760)	1
  (40135, 21385)	1


In [140]:
X = title_bow.toarray()
print(X)
 
X.shape 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(40136, 21473)

In [95]:
# TF-IDF Algo -term frequency-inverse document frequency to know the most significant words

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer=TfidfTransformer().fit(title_bow)
print(tfidf_transformer)

title_tfidf=tfidf_transformer.transform(title_bow)
print(title_tfidf)# got tfidf values for whole vocabulary
print(title_tfidf.shape)  

TfidfTransformer()
  (0, 21317)	0.1684627481925885
  (0, 20576)	0.21645963065595242
  (0, 15886)	0.26521790256580835
  (0, 11848)	0.3663726478188819
  (0, 11532)	0.21950579132713158
  (0, 8924)	0.2945865104560167
  (0, 8919)	0.21181085039722053
  (0, 8694)	0.3663726478188819
  (0, 8568)	0.1726760376919201
  (0, 8022)	0.2369158038432981
  (0, 6211)	0.3130650720056575
  (0, 4198)	0.19912912157390564
  (0, 3862)	0.19856740648703688
  (0, 3035)	0.19808274084498775
  (0, 1775)	0.12411180303215963
  (0, 1739)	0.29742483858599267
  (1, 19171)	0.30873436810420457
  (1, 17917)	0.3151828093756425
  (1, 14436)	0.23714744998696577
  (1, 13926)	0.2830240014437196
  (1, 9317)	0.3350424565466734
  (1, 9208)	0.19805586329024114
  (1, 8924)	0.29932785834393
  (1, 8919)	0.21521993021765556
  (1, 7633)	0.2611863149677818
  :	:
  (40131, 7554)	0.3964261187848613
  (40131, 847)	0.6067492336359531
  (40132, 19614)	0.3398412105348091
  (40132, 7267)	0.7606917419942797
  (40132, 5997)	0.5530425167054914
  (40

In [96]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(
    title_tfidf, # data training 80%
    df['no']
)

In [97]:
all_predictions = model.predict(
    title_tfidf # data uji 20%
)
print(all_predictions)

[3 3 3 ... 8 8 3]


In [98]:
#Printing the confusion matrix of our prediction
from sklearn.metrics import confusion_matrix

confusion_matrix(
    df['no'], 
    all_predictions
)

array([[ 362,    2,   46,  529,    0,    6,  269,   11,  224,    0],
       [   0,  427,  205,  689,    1,    1,  416,    1,  526,    0],
       [   0,    8, 4029,  430,    0,    0,  155,    0,  328,    0],
       [   1,    8,  179, 6913,    2,    1,  757,   11,  705,    1],
       [   1,    0,   13,  379,  412,    2,   75,    1,  162,    0],
       [   5,    0,   36,  677,    0,  202,  447,    4,  269,    0],
       [   0,   16,   45,  742,    1,    1, 7721,   21,  188,    0],
       [   0,    1,   77,  513,    2,    2,  439,  882,  705,    2],
       [   1,    3,  155,  431,    2,    3,  297,   10, 6499,    1],
       [   1,    1,  189,  514,    1,    4,   91,    8,  480,  159]],
      dtype=int64)

In [91]:
# Source
# https://www.youtube.com/watch?v=oq68P8Kv7nE

In [135]:
tweet_judul = ["psikologis"]
tweet1 = tweet_judul

In [138]:
tweet_judul = vectorizer.transform(tweet_judul)
print(tweet1)
p = model.predict(tweet_judul)

AttributeError: lower not found